Justin retina dev
AntreasAntoniou/GATE pull request #4
Opened 2022-04-07 00:04 UTC by justinengelmann

The dataset and datamodule specific tests pass - I'm setting the dotenv for now to avoid redownloading the dataset, but there might be a more elegant way of doing it.

This is a first attempt which seems to work, but I expect that there'll be lots of useful suggestions to be made (style/efficiency/etc.)

I should maybe also add tests for the data download/extraction/preprocessing part, although that shouldn't be changed by other code, so it's less crucial that we have tests for it immediately.

2022-04-10 01:49 UTC, AntreasAntoniou requested changes
Please have a look at comments and give me some feedback

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  dataset_name: cifar100
the name here is generally used for saving purposes, and it seems that cifar100 is a typo

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  modality_config:
Should we have a new modality for medical datasets? CT vs MRI?

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +      width: 32
Is this size the right default?

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - datamodule: kaggle_diabetic_retinopathy_classification.yaml
worth having a slightly different naming for datamodule vs task? I don't mind it but using the term Dataset/Task at the end of the class might help avoid future issues

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +name: ${datamodule.dataset_config.dataset_name}-${model.model_name_to_download}-${seed}
May worth having a better name building structure (I wanted to do this for my own stuff too, I'll take care of it in future pull requests)

2022-04-10 01:49 UTC, AntreasAntoniou commented on gate/class_configs/base.py
> +    remove_raw: bool = False
remove_raw and remove_archives would benefit from a comment that explains what they do (in the future we should build a proper autodoc function)

2022-04-10 01:49 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        # Could this and the next block be moved to the base class?
Yes, we could do that.

2022-04-10 01:49 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        # This is taken from the CIFAR datamodule, however should the data module contain baked in task specific stuff?
The datamodule will know the exact shape of the input_data as it literally generates it. The way I see it. DataModule sets input shapes, and TaskModules set output shapes.

2022-04-10 01:49 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +    def _get_transforms(self):
nice :+1:

2022-04-10 01:49 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +batch_size: 64
:+1:

2022-04-10 01:52 UTC, AntreasAntoniou requested changes
Have a look at comments, for the most part it seems I was looking at the wrong commit earlier

2022-04-10 01:52 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  dataset_name: kaggle_diabetic_retinopathy
Apparently I was looking at the wrong commit earlier. Much better.

2022-04-10 01:52 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +      height: 512
:+1:  Seems I was looking at wrong commit.

2022-04-10 01:52 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - task: kaggle_diabetic_retinopathy_image_classification.yaml
Look who is reading my mind.

2022-04-10 01:52 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        self.dataset_root = pathlib.Path(dataset_config.dataset_root)
:+1:

2022-04-10 01:52 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +            log.warning(f'CAUTION: Failed to preprocess img {img_path} due to the following exception: {e}. '
Try to use emojis -- why? Because they might life more fun ;)

2022-04-10 01:54 UTC, AntreasAntoniou commented on configs/model/ImageAdaptiveViT.yaml
> +    dtype: float32
:muscle:

2022-04-10 01:54 UTC, AntreasAntoniou commented on gate/datasets/kaggle_diabetic_retinopathy.py
> +        self.img_dir = pathlib.Path(root) / 'train_preprocessed'
:+1:

2022-04-10 01:54 UTC, AntreasAntoniou commented on gate/tests/unit/datamodules/test_kaggle_diabetic_retinopathy_datamodule.py
> +        assert x["image"].shape == (batch_size, 3, 512, 521)
Typo? 521 -> 512

2022-04-10 16:51 UTC, justinengelmann commented on gate/tests/unit/datamodules/test_kaggle_diabetic_retinopathy_datamodule.py
> +        assert x["image"].shape == (batch_size, 3, 512, 521)
Ah yes, I hadn't pushed the latest commit 🤦 😮‍💨 😅

2022-04-10 16:51 UTC, justinengelmann commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +            log.warning(f'CAUTION: Failed to preprocess img {img_path} due to the following exception: {e}. '
⚠️⚠️⚠️

2022-04-10 16:52 UTC, justinengelmann commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - task: kaggle_diabetic_retinopathy_image_classification.yaml
my time machine is coming in handy 😏

2022-04-10 17:02 UTC, justinengelmann commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        # This is taken from the CIFAR datamodule, however should the data module contain baked in task specific stuff?
Here I was talking about the line below (66 here)
The cifar datamodules and thus this one, too, have a line like
        self.output_shape_dict = {"image": dict(num_classes=5)}
however, that 5/10/100, and ideally the entire dict should come from the task somehow (I think)

2022-04-10 17:06 UTC, justinengelmann commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        # Could this and the next block be moved to the base class?
Made an issue for it so we remember

2022-04-10 17:11 UTC, justinengelmann commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - datamodule: kaggle_diabetic_retinopathy_classification.yaml
Yeah, I think that's a good idea - maybe when we stop baking in the num_classes inside the dataloader we also change this config?

2022-04-10 17:14 UTC, justinengelmann commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  modality_config:
Let's discuss this. Generically, an image is a 3d input with one dimension ("channel") being substantially smaller than the other dims, most commonly c=3 or c=1
CT/MRI are true 3d inputs, so maybe those would be 3d imaging data?

-- Right now, we also don't consider/support cases where we get multiple images (say front and side view of an object), so we might want to think about how best to extend it if and when we need it.

2022-04-10 17:15 UTC, justinengelmann commented on gate/class_configs/base.py
> +    remove_raw: bool = False
Yes, good point - where should we document them best though? In the yaml? or in base.py? Python code is where  I am used to seeing it, but configs are what's actually edited.

2022-04-14 00:30 UTC, AntreasAntoniou commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  modality_config:
I think the modality categories exist for two reasons:
1. To inform the programmer/user about what it supports in human readable form
2. To facilitate a common language in the model/learner/task such that they can easily speak to each other about the data they receive and their expected shapes/dimensions. 

Because of this I would not be against having one modality for each modality type, i.e. CT, MRI, Video, MultiViewImage. Alternatively we could consider more general categories in the form of 1D, 2D, 3D, 4D tensor modalities, or something more specific, such as considering multi-view images as 'Videos' and CT+MRI as 3D medical data. I lean more towards the first choice to be honest.

2022-04-14 00:32 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - datamodule: kaggle_diabetic_retinopathy_classification.yaml
Can you show me an example?

2022-04-14 00:33 UTC, AntreasAntoniou commented on gate/class_configs/base.py
> +    remove_raw: bool = False
We should document it in the python code, then perhaps copy paste the same entries in the yaml, or maybe automate this process

2022-04-14 00:34 UTC, AntreasAntoniou commented on gate/datamodules/kaggle_diabetic_retinopathy.py
> +        # This is taken from the CIFAR datamodule, however should the data module contain baked in task specific stuff?
I feel like the dataset output and task output shapes can be different, as one may choose to use the original labels or not to generate some other task output shape. And at the same time we don't want to mess with the dataset a lot. Does this make sense?

2022-04-14 12:55 UTC, justinengelmann commented on configs/datamodule/kaggle_diabetic_retinopathy.yaml
> +  modality_config:
Sounds reasonable - I think the first option moves a bit away from the idea of being very general, which might be a good idea. I was thinking about the image/audio/text/video distinction that's in the code in various. That's quite abstract.

In any case, I agree that what you describe should be apparent from the code and for any non-standard dataset, we ideally write a small description of what's going on. (I.e. what's a retinal image, how is it taken, what's diabetic retinopathy, what are the grades/classes)

2022-04-14 12:57 UTC, justinengelmann commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - datamodule: kaggle_diabetic_retinopathy_classification.yaml
Sure, I'm thinking about this https://github.com/AntreasAntoniou/GATE/blob/d6f056a2baedf6ebbd3c3cad05765788b1346fe8/gate/datamodules/cifar.py#L38
- It's not a CIFAR10ImageClassifcationDataModule, but it still bakes in the outputshape dict for classification.

2022-04-14 12:58 UTC, justinengelmann commented on gate/class_configs/base.py
> +    remove_raw: bool = False
That sounds reasonable. On second thought, do we want that in base.py or in the datamodule code?

2022-04-14 16:21 UTC, AntreasAntoniou commented on configs/kaggle_diabetic_retinopathy.yaml
> +  - datamodule: kaggle_diabetic_retinopathy_classification.yaml
Sounds good to me.

2022-04-14 16:22 UTC, AntreasAntoniou commented on gate/class_configs/base.py
> +    remove_raw: bool = False
Always go for base if it has the elements you want explained, we can use inherited docs to push the docs upstream in abraction space.

2022-09-02 23:07 UTC, closed without merging